version: 2
defaults: &defaults
  steps:
    - checkout
    - run:
        command: bundle install && bundle exec rake

jobs:
  ruby_2.6.0:
    docker:
       - image: circleci/ruby:2.6.0
    <<: *defaults

  ruby_2.5.3:
    docker:
       - image: circleci/ruby:2.5.3
    <<: *defaults

  ruby_2.4.5:
    docker:
       - image: circleci/ruby:2.4.5
    <<: *defaults

workflows:
  version: 2
  test_all_versions:
    jobs:
      - ruby_2.6.0
      - ruby_2.5.3
      - ruby_2.4.5
